// <auto-generated />
using System;
using ApiAngular.Infra.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiAngular.Migrations
{
    [DbContext(typeof(ApiAngularContext))]
    [Migration("20180914013559_ContextMigration")]
    partial class ContextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiAngular.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_customer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("nm_customer")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("customer","dbo");
                });

            modelBuilder.Entity("ApiAngular.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_document");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("dc_document")
                        .HasMaxLength(100);

                    b.Property<Guid>("IdCustomer")
                        .HasColumnName("id_customer");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnName("init_document")
                        .HasMaxLength(20);

                    b.Property<int>("Status")
                        .HasColumnName("id_status");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("Initials")
                        .IsUnique();

                    b.ToTable("document","dbo");
                });

            modelBuilder.Entity("ApiAngular.Models.Document", b =>
                {
                    b.HasOne("ApiAngular.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
